version: '2'
services:
  ubuntu:
    build: 
      context: .
      dockerfile: dockerfile-kasm-desktop-alex
    restart: unless-stopped
    container_name: ubuntu
    shm_size: '2gb'
    ports:
      - '6901:6901'
    environment:
      VNC_PW: ptL7DfG6hXVqEU
    networks:
      - nginx-proxy-manager

networks:
  nginx-proxy-manager:
    # WARNING: You should create it first. Use: 'docker network create nginx-proxy'
    external: true